import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Box } from "@chakra-ui/react";
import { useGetTodosQuery } from "@/services/todoService";
import {
  Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
  TableCaption,
  TableContainer,
  Heading,
  Tag,
  TagLabel,
} from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { data: todosList } = useGetTodosQuery();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        display={"flex"}
        flexDir={"column"}
        gap={10}
        w={"100%"}
        h={"100vh"}
        bg={"white"}
        p={16}
      >
        <Heading as="h6" size="xs">
          Todos Table
        </Heading>
        <TableContainer>
          <Table variant="striped">
            <Thead>
              <Tr>
                <Th>id</Th>
                <Th>title</Th>
                <Th>description</Th>
                <Th>status</Th>
              </Tr>
            </Thead>
            <Tbody>
              {todosList?.map((todo) => {
                return (
                  <Tr key={todo.id}>
                    <Td>{todo.id}</Td>
                    <Td>{todo.title}</Td>
                    <Td>{todo.description}</Td>
                    <Td>
                      <Tag
                        variant="outline"
                        colorScheme={todo.done ? "green" : "red"}
                      >
                        <TagLabel>{todo.done ? "done" : "not done"}</TagLabel>
                      </Tag>
                    </Td>
                  </Tr>
                );
              })}
            </Tbody>
          </Table>
        </TableContainer>
      </Box>
    </>
  );
}
