import Head from "next/head";
import { Box, Stack, Skeleton } from "@chakra-ui/react";
import { useGetTodosQuery } from "@/services/todoService";
import { Heading } from "@chakra-ui/react";
import TododsTable from "./TodosTable";

export default function Home() {
  const { data: todosList, isLoading: todosLoading } = useGetTodosQuery();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box
        display={"flex"}
        flexDir={"column"}
        gap={10}
        w={"100%"}
        h={"100vh"}
        bg={"white"}
        p={16}
      >
        <Heading as="h6" size="xs">
          Todos Table
        </Heading>
        {todosList && <TododsTable todosList={todosList} />}
        {todosLoading && (
          <Stack>
            <Skeleton height="40px" />
            <Skeleton height="40px" />
            <Skeleton height="40px" />
          </Stack>
        )}
      </Box>
    </>
  );
}
